"""add match_reasoning and match_scored_at

Revision ID: 120d544dfd3f
Revises: eb01e32a3cb4
Create Date: 2026-07-23 02:07:57.336559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  


# revision identifiers, used by Alembic.
revision: str = '120d544dfd3f'
down_revision: Union[str, Sequence[str], None] = 'eb01e32a3cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobposting', sa.Column('match_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobposting', sa.Column('match_scored_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobposting', 'match_scored_at')
    op.drop_column('jobposting', 'match_reasoning')
    # ### end Alembic commands ###
